import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import { getApiLimitCount } from '@/lib/api-limit'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function DashBoardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const apiLimitCount = await getApiLimitCount();
  return (
    <div className="h-full relative">
    <div className="hidden h-full md:flex md:w-72 md:flex-col md:fixed md:inset-y-0 z-80 bg-gray-900">
      <Sidebar apiLimitCount={apiLimitCount}  />
    </div>
    <main className="md:pl-72 pb-10">
      <Navbar apiLimitCount={apiLimitCount} />
      {children}
    </main>
  </div>
  )
}
